---
# tasks file for debian-preconf

- name: add apt proxy settings
  lineinfile: "dest=/etc/apt/apt.conf.d/01proxy create=yes line='{{ preconf_apt_proxy_line }}'"

- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: install packages
  apt: pkg={{item}} state=latest
  with_items:
  - mc
  - less
  - tcpdump
  - vim
  - openssh-server
  - sudo
  - screen
  - lsb-release
  - cron
  - debian-archive-keyring
  - bash
  - libc6
  - aptitude
  - ntpdate
  - tzdata

- name: remove notneeded packages 
  apt: pkg=network-manager state=absent

- name: add history logging
  lineinfile: dest=/etc/profile.d/history.sh insertafter=EOF create=yes line="{{item}}"
  with_items: 
    - export HISTFILESIZE=9999
    - export HISTTIMEFORMAT=\"%F %T \"
  

- name: add ssh keys for root
  authorized_key: user=root key="{{ item.key }}"
  with_items: preconf_root_ssh_keys

- name: add locales
  lineinfile: dest=/etc/locale.gen insertafter=EOF line="{{item}}" regexp=".*{{item}}.*"
  with_items: 
    - ru_RU.UTF-8 UTF-8
    - en_US.UTF-8 UTF-8
  notify:
  - localegen

- name: setup timezone
  lineinfile: dest=/etc/timezone line="{{ preconf_timezone }}" regexp=".*/.*"
  notify:
  - update-timezone

- name: add time syncronization
  cron: name="ntpdate" minute="0" job="/usr/sbin/ntpdate-debian >/dev/null 2>&1"

- name: add custom PS1 line
  lineinfile: dest=/etc/profile.d/ps1.sh create=yes line="PS1=\'\\u@`hostname -f | cut -d\".\" -f1,2`:\\w\\$ \'"

